### ISSUE TITLE
There is an automation-friendly environment for testing the Conjur Puppet module with Windows

### ISSUE THREAD

**Issue by izgeri** [cyberark/conjur-puppet#96]
The goal here is to have a Windows environment that makes running automated tests as simple as running automated tests in Linux environments. Docker containers are used extensively as the quick-to-provision, throw away Linux environments for running tests and carrying out development. They provide a convenient API that allows developers to focus on the bash scripts and the content of their automation tasks. We aspire to something similar for Windows.

The goals for this particular environment are as follows:
1. Run different versions of the puppet agent on Windows (>= v5)
2. Fast startup and teardown
3. Development friendly. A developer should be able to use this environment from their local
4. The test suite is currently written in bash. Many of the components run on Linux (e.g. Puppet Server). Tests on Windows are simply an addition and should be thought of as a bash function `runPuppetAgent` that takes some configuration arguments. `runPuppetAgent` will be called many times from the bash scripts with different configurations. 

Some requirements to be aware of from Puppet:
1. The  Conjur Puppet module requires that the agent and server must both be able to access the Conjur server from the same URL. So if the the URL is `http://conjur:1234`, then this URL must be reachable as is to both the agent and server
2. The puppet agent needs to able to reach the puppet server (under some predefined hostname .e.g `puppet`)

**Comment by izgeri** [comment]
@doodlesbykumbi please add more info to this card - both about the "definition of done" for the env you are creating and any notes you have for what you've done so far. thanks!

**Comment by doodlesbykumbi** [comment]
The current approach I've taken is to use Windows containers. These are available from a variety of places but for my tests I used a EC2 Windows VM with Windows containers. The setup should be the same regardless of the VM provider.

The idea is to make the Docker daemon with Windows containers available to the Linux/OSX environment where the bash scripts are run. This allows us to meet goal (4) from the issue description.

At a high level the approach is
1. Run a Windows VM
2. ssh port forward the Docker daemon so that it's available for the automation scripts
3. ssh port forward so that any resources local to the automation scripts can be made available on the Windows VM (e.g. Conjur/Puppet Server, which are both likely running in Docker on the daemon local to the automation scripts)
4. Run any Windows specific tasks on Windows containers.

Below is an example implementation of the above. Below I assume password authentication for SSH (this would likely be cert based in prod). The auth creds can probably be kept in a vault available to the CI runner (whatever that ends up being).

```
#!/usr/bin/env bash

set -e

windowsVMAddress=X.X.X.X
windowsVMUser=XXX
windowsVMPass=XXX

puppetAgentImage="puppet-agent-v6"
puppetPort="30302"
conjurPort="8081"

conjurUrl="http://conjur:${conjurPort}"
conjurLogin="host/node01"
conjurAccount="cucumber"
conjurVersion="5"
conjurApiToken="1xa2bz57efmxc3s0qvnk2svzx4y1g2xpa1171g14d2866ew7rnnrqe"

# SSH port forwarding of 
# 1. Remote forwarding Puppet port and Conjur port so that it is available in the windows VM
# 2. Local forwarding to expose the Docker daemon locally
# This command also executes sleep for a 100s, this just makes sure if the run isn't done in that time then there's automatic cleanup.
sshpass -p "${windowsVMPass}" \
  ssh \
  -o GatewayPorts=true -T \
  -R "${puppetPort}:localhost:${puppetPort}" \
  -R "${conjurPort}:localhost:${conjurPort}" \
  -L 2375:localhost:2376 \
  "${windowsVMUser}@${windowsVMAddress}" \
  powershell Start-Sleep -s 100 &
portForwardPid=$!

# Ensure cleanup for port forwader
trap "kill -9 ${portForwardPid}" EXIT

# Sleep to ensure port forwarding has been established
sleep 5

# Set DOCKER_HOST so that local CLI uses remote windows Docker daemon
export DOCKER_HOST="tcp://localhost:2375"

# Create test script
cat << EOL > ./test.ps1
# Update hosts file so that 'conjur' and 'puppet' are resolvable
\$hostIp = (ipconfig | where-object {\$_ -match "Default Gateway"} | foreach-object{\$_.Split(":")[1].trim()})
Add-Content -Path "c:\Windows\System32\Drivers\etc\hosts" -Value "\${hostIp} conjur"
Add-Content -Path "c:\Windows\System32\Drivers\etc\hosts" -Value "\${hostIp} puppet"

# Needed to run Conjur flow in the Puppet manifest
\$env:FACTER_CONJUR_SMOKE_TEST="true"

# Make tmp directory in anticipation for file that will be created by Puppet
mkdir tmp

# Set conjur.conf equivalent using Regedit
reg ADD HKLM\Software\CyberArk\Conjur /v ApplianceUrl /t REG_SZ /d ${conjurUrl}
reg ADD HKLM\Software\CyberArk\Conjur /v Version /t REG_DWORD /d ${conjurVersion}
reg ADD HKLM\Software\CyberArk\Conjur /v Account /t REG_SZ /d ${conjurAccount}

# Set conjur.identity equivalent using Windows Credentials Manager
cmdkey /generic:${conjurUrl} /user:${conjurLogin} /pass:${conjurApiToken}

# Puppet agent one time run
puppet agent -t --onetime -v --debug --detailed-exitcodes --masterport ${puppetPort}
EOL

docker rm -f testing || true

# Set up test container and copy test script since volume mounting is not available
docker run --name testing -d --rm "${puppetAgentImage}" powershell -Command "Start-Sleep -s 100"
docker cp "./test.ps1" "testing:test.ps1"

# Run tests
docker exec testing powershell ./test.ps1

# Cleanup
docker rm -f testing
rm ./test.ps1
```

**Comment by doodlesbykumbi** [comment]
This approach has been successful as a means for testing `v5 agent -> v5 server`, and  `v6 agent -> v6 server`, see https://github.com/cyberark/conjur-puppet/issues/84#issuecomment-653176042.

**Comment by izgeri** [comment]
@doodlesbykumbi thanks for adding all of this info! which windows server version have you been testing with? if 2016, would 2012 also work for this approach?

**Comment by doodlesbykumbi** [comment]
So I should have added that I'm running the tests using images I built myself, `puppet-agent-v6` and `puppet-agent-v5`.
They are made from windows server 2018, shown below. As far as I can tell, the containers available are 2016 and above. 2012 will likely need an actual VM.

```
echo "
FROM mcr.microsoft.com/windows/servercore:1809

RUN powershell wget https://downloads.puppetlabs.com/windows/puppet6/puppet-agent-x64-latest.msi -outfile puppet6.msi
RUN powershell wget https://downloads.puppetlabs.com/windows/puppet5/puppet-agent-x64-latest.msi -outfile puppet5.msi
" | docker build -t puppet-agent-dev -

echo "
FROM puppet-agent-dev

RUN powershell Start-Process msiexec.exe -Wait -ArgumentList '/qn /quiet /norestart /L*v C:\puppet_install_log.txt /i C:\puppet5.msi PUPPET_AGENT_STARTUP_MODE=Manual'
" | docker build -t puppet-agent-v5 -

echo "
FROM puppet-agent-dev

RUN powershell Start-Process msiexec.exe -Wait -ArgumentList '/qn /quiet /norestart /L*v C:\puppet_install_log.txt /i C:\puppet6.msi PUPPET_AGENT_STARTUP_MODE=Manual'
" | docker -t puppet-agent-v6 -
```

**Comment by izgeri** [comment]
thanks! we should at least add 2016 to our test flows, and we'll probably need to manually validate 2012. it would help if we understood the difference between these versions better as it applies to how we use them in our module.

**Comment by sgnn7** [comment]
Looks like Win2012 + docker won't be doable at least according to this 🧵: https://forums.docker.com/t/windows-server-2012-r2/24267/2

**Comment by doodlesbykumbi** [comment]
A note on the limitations of windows container.
> Because Windows Server containers and the underlying host share a single kernel, the container's base image OS version must match that of the host. If the versions are different, the container may start, but full functionally isn't guaranteed.

**Comment by doodlesbykumbi** [comment]
With the limitations above in mind, any environments for Windows Server Pre 2016 will require provisioning VMs.

**Comment by izgeri** [comment]
@doodlesbykumbi do you think there's enough docs here that if someone wanted to stand up a similar environment on their own, they'd be able to do it? if so, then I think this can be closed. if not, then can we look at adding any info that's missing? thanks!

**Comment by doodlesbykumbi** [comment]
@izgeri The only thing missing is how to setup the windows VM with windows containers. I'll add it below

**Comment by doodlesbykumbi** [comment]
To setup a Windows VM with windows containers ready to accommodate the flow above:
+ Run `Microsoft Windows Server 2019 with Containers Locale English AMI provided by Amazon` on AWS EC2
+ Expose Docker daemon on TCP port (in addition to the preconfigured pipe), see https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-docker/configure-docker-daemon#configure-docker-with-a-configuration-file. Loosely you need to set the value of the hosts key in the daemon.json file to `["tcp://0.0.0.0:2376", "npipe://"]`. The configuration file can be found at `C:\ProgramData\Docker\config\daemon.json`.
+ Setup SSH server and ensure port is open in AWS security group, and Windows firewall
+ Set GatewayPorts to yes for SSH https://www.ssh.com/ssh/tunneling/example. As best I understand this is because the docker containers and the host are connected via a gateway and you want any port-forwards (from the testing remote host) to be reachable from containers.
+ Open any ports you might need in the Windows firewall. I think any port that is forwarded must be open so that it is accessible within containers over the gateway. Test this
+ Test this VM so that you can prove connectivity via port-forwards to-and-from containers and the testing remote host.
+ Save as a new AMI
